#!/bin/bash
#
# Delete the directories generated by the packaging

rm -rf NaivePhysicsProject/Binaries/
rm -rf NaivePhysicsProject/Build/
rm -rf NaivePhysicsProject/DerivedDataCache/
rm -rf NaivePhysicsProject/Intermediate/
rm -rf NaivePhysicsProject/Saved/
rm -rf NaivePhysicsProject/LinuxNoEditor/
