#!/bin/bash
#
# Delete the directories generated by the NaivePhysics packaging
# process (this do nopt remove UnrealEngine or lua/torch)

rm -rf NaivePhysics/Binaries/
rm -rf NaivePhysics/Build/
rm -rf NaivePhysics/DerivedDataCache/
rm -rf NaivePhysics/Intermediate/
rm -rf NaivePhysics/Saved/
rm -rf NaivePhysics/LinuxNoEditor/
